default: &default
  redis_url:
    <%= ENV['REDISTOGO_URL'] || ENV['REDIS_URL'] || 'redis://localhost:6379/1'%>
  sidekiq:
    username: <%= ENV['SIDEKIQ_USERNAME'] %>
    password: <%= ENV['SIDEKIQ_PASSWORD'] %>

development:
  <<: *default
  secret_key_base: 5193ce62de10f78da223e95760dd6c08523cd78204b4d8dc8bb119faf8847adceb70aadce1288ffd8e6232afb3a704c60a75feb024ab937de989322f4e64a385

test:
  <<: *default
  secret_key_base: 18523cd7820d8e6232afb3a704c60a75feb024ab937de989322f4e64a3854b4d8dc8bb119faf8847adceb70aadce1288ff3193ce62de10f78da223e95760dd6c

staging:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
